{% set version = "0.7-9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-varselrf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/varSelRF_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/varSelRF/varSelRF_{{ version }}.tar.gz
  sha256: 05a2e00c90c7c5196138bf1f3c43665a19eef2a182c361f59ebca059ea545f6c

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-randomforest
  run:
    - r-base
    - r-randomforest

test:
  commands:
    - $R -e "library('varSelRF')"           # [not win]
    - "\"%R%\" -e \"library('varSelRF')\""  # [win]

about:
  home: http://ligarto.org/rdiaz/Software/Software.html, http://ligarto.org/rdiaz/Papers/rfVS/randomForestVarSel.html, https://github.com/rdiaz02/varSelRF
  license: GPL-2.0-or-later
  summary: 'Variable selection from random forests using both backwards variable elimination (for the selection of small sets of non-redundant variables) and selection based on the importance spectrum (somewhat similar to scree plots; for the selection of large, potentially highly-correlated variables). Main applications
    in high-dimensional data (e.g., microarray data, and other genomics and proteomics applications). '
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: varSelRF
# Version: 0.7-8
# Date: 2017-07-10
# Title: Variable Selection using Random Forests
# Author: Ramon Diaz-Uriarte <rdiaz02@gmail.com>
# Maintainer: Ramon Diaz-Uriarte <rdiaz02@gmail.com>
# Depends: R (>= 2.0.0), randomForest, parallel
# Description: Variable selection from random forests using both backwards variable elimination (for the selection of small sets of non-redundant variables) and selection based on the importance spectrum (somewhat similar to scree plots; for the selection of large, potentially highly-correlated variables). Main applications in high-dimensional data (e.g., microarray data, and other genomics and proteomics applications).
# LazyLoad: Yes
# License: GPL (>= 2)
# URL: http://ligarto.org/rdiaz/Software/Software.html, http://ligarto.org/rdiaz/Papers/rfVS/randomForestVarSel.html, https://github.com/rdiaz02/varSelRF
# Repository: CRAN
# Date/Publication: 2017-07-10 13:54:22 UTC
# Packaged: 2017-07-10 10:47:03.738 UTC; ramon
# NeedsCompilation: no
