appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: rS2y/H8sylgBa+UB4RNsxD9wNxfIJoUcUjKLI10l2oXOzqH4Cjf+7Z8rewLzG3uvWvDVWdegRwZFpqt8O2/xKa6srDy33oLxbu2rFZ37+7Jm2BgkcS6wU9y4xlS65lGS3OAfhnNV6Aj3mMGpr84K2Za6YyY0xdJ734OxA64OUNOGeS64CkCZZ4fZqhwy0exs32IRQHSGBzkGW7H/j1JeaAmkm14/PdmRfsWq08eUHKuMlzhmfSWoWEDBe2c38abhLK4cprQ5bUPMTA/CvQvx7KWcQO+dZJBROx+BcMDAH2IhTP/FtccZ4eeFVxSAO3HPZJOAaGWai4iVnzlmWxmjc30gR/0SDHwE4jplU1ZEY4DmrxuytZRYm3HFY+UOHx6MiBmO8o/XMsT7lIfKdhabMuYWOucfM4qzLZyjRByOyMgEbeyHPQrfo0561Rca8SSfYsBmNZW2AzQn74uvpKWvHQpIbV8M23WarbCYC40ryvftHjoeFdop1Sostekc+eIY+hCcvdwp3hmnCXe2USF173p77XFQJmcH5ifbUArOjzxcbCyIRAIFDRL2eRzE7n9cUN/Pq76pE2fXqM3/46ftaVuxImsae4xeeFqLFK5I/zb2IY8EmKhBTXv7BADTeHCzOHYyKK8RRYelrKw30Qk8Iqz8eLXY1jQkZ2SjERAaucU=
